name: Release App
  # You may pin to the exact commit or the version.
  # uses: subosito/flutter-action@48cafc24713cca54bbe03cdc3a423187d413aafa
    
on:
  push:
     branches: [ main ]
     
jobs:
 retrievingVersion:
  runs-on: ubuntu-latest
  outputs:
      version: ${{ steps.versionstep.outputs.version }}
  steps:
    - uses: actions/checkout@v3
    - name: Retrieve Release Version
      id: versionstep
      working-directory: jackbox_patcher
      run: |
         VERSION=$(more pubspec.yaml | grep version: | cut -d ' ' -f2)
         echo "version=${VERSION}" >> $GITHUB_OUTPUT
 build_windows:
   runs-on: windows-latest
   needs: retrievingVersion
   steps:
     - uses: actions/checkout@v3
     - uses: subosito/flutter-action@v2
       with:
        flutter-version: '3.10.0'
        channel: 'stable'
     - name: Build windows
       working-directory: ./jackbox_patcher
       run: flutter build windows --build-name ${{ needs.retrievingVersion.outputs.version }} -t ./lib/main_release.dart
     - uses: actions/upload-artifact@v3
       with:
          name: build_windows
          path: ./jackbox_patcher/build/windows/runner/Release
 build_linux:
   runs-on: ubuntu-latest
   needs: retrievingVersion
   steps:
     - uses: actions/checkout@v3
     - run: |
        sudo apt-get update -y
        sudo apt install libmpv-dev mpv
        sudo apt-get install -y ninja-build libgtk-3-dev
        sudo apt-get install -y libunwind-dev libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev libgstreamer-plugins-bad1.0-dev gstreamer1.0-plugins-base gstreamer1.0-plugins-good gstreamer1.0-plugins-bad gstreamer1.0-plugins-ugly gstreamer1.0-libav gstreamer1.0-tools gstreamer1.0-x gstreamer1.0-alsa gstreamer1.0-gl gstreamer1.0-gtk3 gstreamer1.0-qt5 gstreamer1.0-pulseaudio
     - uses: subosito/flutter-action@v2
       with:
        flutter-version: '3.10.0'
        channel: 'stable'
     - name: Build linux
       working-directory: ./jackbox_patcher
       run: flutter build linux --build-name ${{ needs.retrievingVersion.outputs.version }} -t ./lib/main_release.dart
     - uses: actions/upload-artifact@v3
       with:
          name: build_linux
          path: ./jackbox_patcher/build/linux/x64/release/bundle
 upload:
    runs-on: ubuntu-latest
    needs: 
      - build_windows
      - build_linux
      - retrievingVersion
    steps: 
      - run: mkdir -p dist
      - uses: actions/download-artifact@master
        with:
          name: build_windows
          path: dist/JackboxUtility_Windows
      - uses: actions/download-artifact@master
        with:
          name: build_linux
          path: dist/JackboxUtility_Linux
      - name: Zipping windows release
        working-directory: dist/JackboxUtility_Windows
        run: |
          zip -r ../../JackboxUtility_Windows.zip *
      - name: Zipping linux release
        working-directory: dist/JackboxUtility_Linux
        run: |
          zip -r ../../JackboxUtility_Linux.zip *
      - name: Upload release onto Github
        uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: /home/runner/work/JackboxRutility/
  
